ARG BASE_TAG=1.18.0-rolling-daily
FROM kasmweb/chromium:${BASE_TAG}

LABEL org.opencontainers.image.title="Kasm CyberChef Workspace"
LABEL org.opencontainers.image.description="Thin multi-arch Kasm Chromium wrapper for CyberChef."
LABEL org.opencontainers.image.source="https://github.com/alove4tech/kasm-registry"
LABEL org.opencontainers.image.url="https://gchq.github.io/CyberChef/"

ENV LAUNCH_URL="https://gchq.github.io/CyberChef/"
